spring:
  application:
    name:
      DoranDroan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}
    mongodb:
      uri: ${MONGO_URI}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
  cors:
    allowed-origin: ${CORS_ORIGIN}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SERVER_EMAIL}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
        expiration: 3600000


jwt:
  access:
    secret: ${JWT_ACCESS_KEY}
    expiration: ${JWT_ACCESS_EXP}  # 30분
  refresh:
    secret: ${JWT_REFRESH_KEY}
    expiration: ${JWT_REFRESH_EXP}  # 7일


cloud:
  aws:
    s3:
      bucket: dorandoran-img
    region:
      static: ap-northeast-2

logging:
  level:
    org.springframework.mail: DEBUG
    org.apache.commons.mail: DEBUG