spring:
  application:
    name:
      DoranDroan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
  cors:
    allowed-origin: ${CORS_ORIGIN}
jwt:
  access:
    secret: ${JWT_ACCESS_KEY}
    expiration: ${JWT_ACCESS_EXP}  # 30분
  refresh:
    secret: ${JWT_REFRESH_KEY}
    expiration: ${JWT_REFRESH_EXP}  # 7일